name: 'Prepare Node.js'

runs:
    using: 'composite'
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
              node-version: 16
        - name: Install dependencies
          run: npm ci
