name: Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    VITE_APPWRITE_ENDPOINT: http://appwrite.test/v1

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16
            - name: Audit dependencies
              run: npm audit --audit-level high
            - name: Install dependencies
              run: npm ci
            - name: Build Console
              run: npm run build
    diagnostics:
        name: Diagnostics
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Svelte Diagnostics
              run: npm run check
    linter:
        name: Linter
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Linter
              run: npm run lint
    unit-tests:
        name: Unit Tests
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Unit Tests
              run: npm test
    e2e-tests:
        name: E2E Tests
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: E2E Tests
              run: |
                  npx playwright install
                  npm run e2e
