name: Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    VITE_APPWRITE_ENDPOINT: http://appwrite.test/v1

jobs:
    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/workflows/prepare.yml
            - name: Audit dependencies
              run: npm audit --audit-level high
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/workflows/prepare.yml
            - name: Install dependencies
              run: npm ci
            - name: Build Console
              run: npm run build
    diagnostics:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/workflows/prepare.yml
            - name: Svelte Diagnostics
              run: npm run check
    linter:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/workflows/prepare.yml
            - name: Linter
              run: npm run lint
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/workflows/prepare.yml
            - name: Unit Tests
              run: npm test
    e2e-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/workflows/prepare.yml
            - name: E2E Tests
              run: |
                  npx playwright install
                  npm run e2e
